name: main
on: push
env:
  PYTHON_VERSION: 3.10

jobs:
  test-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: test get-function
        run: cd cloud-resume-challenge/get-function && python -m unittest discover

      # - name: test put-function
      #   run: cd cloud-resume-challenge/put-function && python -m unittest discover